name: agrovision
description: A smart farming companion app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  http: ^1.3.6
  intl: ^0.20.2
  flutter_carousel_widget: ^3.1.0
  carousel_slider: ^5.0.0
  #image_picker: ^1.0.4
  csv: ^6.0.0
  #camera: ^0.11.1
  google_mlkit_commons: ^0.11.0
  google_mlkit_image_labeling: ^0.14.1
  #path_provider: 
  path:
  file_selector: ^1.0.3
  json_annotation: ^4.8.1
  geolocator: ^14.0.0
  # Downgraded to a compatible version
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
  # flutter_sound: ^8.4.6  # Removed flutter_sound dependency
  permission_handler: ^12.0.0+1
  #camera: ^0.9.4+5
  google_fonts: ^6.1.0
  url_launcher: ^6.2.5
  flutter_svg: ^2.0.10+1
  #image: ^3.3.0
  tflite_flutter: ^0.11.0
  camera: ^0.11.1
  path_provider: ^2.0.12
  image: ^4.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/crop_data.csv
    - assets/images/crop.png
    - assets/images/crop1.png
    - assets/images/home.png
    - assets/plant_data.json
    - assets/xyz.jpg
    - assets/image/google-icon-logo-svgrepo-com.svg
    - assets/best_float32.tflite
    - assets/labels.txt
